steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/katanasa-app:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/katanasa-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'katanasa-app'
      - '--image=gcr.io/$PROJECT_ID/katanasa-app:$COMMIT_SHA'
      - '--set-env-vars=ENVIRONMENT=Live,DATABASE=xxxx,SAFARICOM_IP_ADDRESS_VALIDATION=true'
      - '--region=us-central1'
      - '--project=$PROJECT_ID'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'katanasa-app'
      - '--to-latest'
      - '--region=us-central1'
      - '--project=$PROJECT_ID'
